server:
  port: 13011
#  servlet:
#    context-path: /yundata



spring:
  rabbitmq:
    host: 192.168.1.99
    port: 5672
    username: guest
    password: guest
    receive: 
      asyn: asyn
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.1.99:9300
  redis:
    database: 4
    host: 192.168.1.99
    port: 6379
    password: 
    timeout: 2000
    jedis:
      pool:
        max-active: 10000
        min-idle: 0
        max-idle: 50
        max-wait: -1
    user:
      database: 11
      host: 192.168.1.99
      port: 6379
      password: 
    admin:
      database: 12
      host: 192.168.1.99
      port: 6379
      password:              
  datasource:
    platform: mysql
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT1FROMDUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
#    filters: stat,wall,log4j
    logSlowSql: true
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.99:3306/db_asyn?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: retow
    password: Retow0594@
    driverClassName: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    
 #聚合短信
third:
  sms:
    juhe:
      url: http://v.juhe.cn/sms/send
      AppKey: aa2a58a26de535e140f38b85987b0b92   
  character:
    path:
      pinyin: py4j.txt
      wubi: wb86.properties  
      
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.his.asyn.repository.model

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql          